use_frameworks!

platform :ios, '13.0'

target 'osp_selfie_Example' do
  pod 'OSPSDK/Selfie', :path => '../'

  
  pod 'Moya'
  pod 'PromiseKit'
  pod 'SwiftMessages'
  
  
  target 'osp_selfie_Tests' do
    inherit! :search_paths

    
  end
end
