use_frameworks!

platform :ios, '11.0'

target 'OSPKit_Objc_demo' do
#  pod 'OSPKit', :path => '../'
#  pod 'OSPSelfie', :path => '../'
#  pod 'OSPDocument', :path => '../'
#  pod 'OSPSelfie'
end


target 'OSPKit_Example' do
#  pod 'OSPKit', :path => '../'
  pod 'OSPSelfie', :path => '../'
#  pod 'OSPDocument', :path => '../'
#  pod 'OSPSelfie'
  target 'OSPKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['SwiftMessages', 'Moya', 'PromiseKit'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
